### ISSUE TITLE
An API error from swagger causes $digest already in progress error

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend#72]
![image](https://cloud.githubusercontent.com/assets/4072455/12375815/3dc1dc4c-bc89-11e5-9fde-e0b5c9b195ec.png)

--
Repro

```javascript
$scope.apply(function () {
  disclosureApi.locations.get(); // Missing required parameters.
});
```
_- added by @adborden_

**Comment by bcipolli** [comment]
When I set up front-end/back-end interactions for #73, I start seeing this on other endpoints. This is now blocking me from making progress.

@adborden @jnmarcus could you take a look? Perhaps it's a setup issue on my end?

**Comment by adborden** [comment]
Looking at this now. I assume this is on the develop branch? One thing I noticed is that the feature/62 PRs were meant to be merged in reverse order. So not all the changes landed right. I'll be more clear about this next time.

**Comment by adborden** [comment]
I can't repro this right now. The a.c.o [endpoint](http://admin.caciviclab.org/docs/#!/search/get) is returning 0 results. Even trying locally after running `xformnetfilerawdata`, I don't have results. Looks like I need to add a ballot before search will actually return any results.

**Comment by adborden** [comment]
Which branch should I be using on the backend?

**Comment by bcipolli** [comment]
`xformnetfilerawdata` always creates a `ballot`, as long as there's 460A data for whatever agencies/years you're loading. It couldn't otherwise--`ballot` is necessary to load any `IndependentMoney`.

This should work on `master`.

**Comment by adborden** [comment]
The root cause is that the parameter on the backend  changed. This is the error I'm seeing.

```
missing required params: locality_id
```

https://github.com/caciviclab/disclosure-frontend-alpha/pull/77 fixes the issue and should unblock you @bcipolli. But there's still a bug in the error handling.

**Comment by bcipolli** [comment]
:+1: thanks! I guess you found the error through the browser's debugger somehow? Any tips on how to locate the error would be appreciated--I wasn't sure how to decompose...

**Comment by adborden** [comment]
@bcipolli it's actually in your screenshot, it just isn't reported as an error, just a regular `console.log`.

**Comment by bcipolli** [comment]
LOL! :+1:

**Comment by bcipolli** [comment]
Fixed in #77

**Comment by adborden** [comment]
I'd leave this open, as there's still an issue with the error handling.

**Comment by jnmarcus** [comment]
Fixed in #114
